### ISSUE TITLE
After last Commits

### ISSUE THREAD

**Issue by m7Name** [Tazi0/new_banking#10]
![image](https://user-images.githubusercontent.com/29282883/59568953-4987c800-908b-11e9-8072-f6f2249157fc.png)

**Comment by abdulkadiraktas** [comment]
I fixed pls check.

**Comment by m7Name** [comment]
nope. still error
![image](https://user-images.githubusercontent.com/29282883/59569373-3b3caa80-9091-11e9-99c9-cc0bb30498f8.png)

**Comment by m7Name** [comment]
"config.lua",  __resource.lua

**Comment by m7Name** [comment]
This one left
![image](https://user-images.githubusercontent.com/29282883/59569441-1bf24d00-9092-11e9-9beb-5c4c8cf95bec.png)

**Comment by abdulkadiraktas** [comment]
I fixed please check these commit 
https://github.com/Tazi0/new_banking/pull/12
https://github.com/Tazi0/new_banking/pull/13
https://github.com/Tazi0/new_banking/pull/14

**Comment by m7Name** [comment]
#14 after config fix ther is no atm on map
a made my own and add atm's  that you miss
https://raw.githubusercontent.com/m7Name/new_banking/patch-1/new_banking/config.lua

**Comment by abdulkadiraktas** [comment]
Ohh yes. I don't show ATM blips on map. :)

**Comment by m7Name** [comment]
![image](https://user-images.githubusercontent.com/29282883/59570048-b8205200-909a-11e9-8085-74e26bc8fccd.png)

I make my own like this

**Comment by abdulkadiraktas** [comment]
By the way. Money send issue fix.
https://github.com/Tazi0/new_banking/pull/15

**Comment by m7Name** [comment]
if you need help with with test will be glad to help

**Comment by abdulkadiraktas** [comment]
My discord ID : Kadir#6390

If you use discord app, you can send a friend request.
