### ISSUE TITLE
Error when opening bank

### ISSUE THREAD

**Issue by MrJaxis** [Tazi0/new_banking#3]
Whenever i open the bank, i cant withdraw or deposit money and i get this error in the server console, can someone help?

Error running system event handling function for resource new_banking: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @new_banking/server.lua:40: attempt to index a nil value (global 'ESX')
stack traceback:
        @new_banking/server.lua:40: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function citizen:/scripting/lua/scheduler.lua:218
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function citizen:/scripting/lua/scheduler.lua:182

**Comment by Tazi0** [comment]
Make sure you have the dependencies installed
